# Generated by Django 2.2 on 2020-11-29 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('finish_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('timeout', models.IntegerField()),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('login_result', models.SmallIntegerField(choices=[(0, 'untri'), (1, 'viewer'), (2, 'client')], default=0)),
                ('failure_reason', models.IntegerField()),
                ('view_client', models.SmallIntegerField(choices=[(0, 'unkown'), (1, 'viewer'), (2, 'client')], default=0)),
                ('login_type', models.BigIntegerField(blank=True, default=None, null=True)),
                ('local_address', models.CharField(blank=True, default=None, max_length=39, null=True)),
                ('remote_address', models.CharField(blank=True, default=None, max_length=39, null=True)),
                ('local_host', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'session',
                'db_table': 'session',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('registred_time', models.DateField()),
                ('password', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('type', models.SmallIntegerField(choices=[(1, 'SystemAdmin'), (2, 'AccountOwner'), (3, 'user')], default=0)),
            ],
            options={
                'verbose_name_plural': 'user',
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('owner', models.OneToOneField(db_column='owner', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='history.User')),
                ('edit_password', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'account_group',
                'db_table': 'account_group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SessionMacAddress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=17)),
                ('session', models.ForeignKey(db_column='session', on_delete=django.db.models.deletion.CASCADE, to='history.Session')),
            ],
            options={
                'verbose_name_plural': 'session_mac_address',
                'db_table': 'session_mac_address',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='P2PSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('src_port', models.PositiveIntegerField()),
                ('dest_port', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
                ('dest_session', models.ForeignKey(db_column='dest_session', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='history.Session')),
                ('src_session', models.ForeignKey(db_column='src_session', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='history.Session')),
            ],
            options={
                'verbose_name_plural': 'p2p_session',
                'db_table': 'p2p_session',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AccountGroupMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('member', models.ForeignKey(db_column='member', on_delete=django.db.models.deletion.CASCADE, to='history.User')),
            ],
            options={
                'verbose_name_plural': 'account_group_member',
                'db_table': 'account_group_member',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='sessionmacaddress',
            constraint=models.UniqueConstraint(fields=('session', 'value'), name='session_session_mac_address_value_unq'),
        ),
        migrations.AddField(
            model_name='accountgroupmember',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.AccountGroup'),
        ),
        migrations.AddConstraint(
            model_name='accountgroupmember',
            constraint=models.UniqueConstraint(fields=('owner', 'member'), name='account_group_member_owner_member_unq'),
        ),
        migrations.AddConstraint(
            model_name='accountgroupmember',
            constraint=models.UniqueConstraint(fields=('member',), name='account_group_member_member_unq'),
        ),
    ]
